/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.academico.view;

/**
 *
 * @author gabriel
 */
public class MontarCronograma extends javax.swing.JInternalFrame {

    /**
     * Creates new form MontarCronograma
     */
    public MontarCronograma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneCronograma = new javax.swing.JScrollPane();
        jTableCronograma = new javax.swing.JTable();
        jLabelTituloCronograma = new javax.swing.JLabel();
        jLabelTurma = new javax.swing.JLabel();
        jLabelCurso = new javax.swing.JLabel();
        jLabelDisciplina = new javax.swing.JLabel();
        jLabelProfessor = new javax.swing.JLabel();
        jSpinnerTurma = new javax.swing.JSpinner();
        jSpinnerProfessor = new javax.swing.JSpinner();
        jSpinnerCurso = new javax.swing.JSpinner();
        jSpinnerDisciplina = new javax.swing.JSpinner();
        jButtonEnviar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTableCronograma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"18:30", null, null, null, null, null, null, null},
                {"19:20", null, null, null, null, null, null, null},
                {"20:10", null, null, null, null, null, null, null},
                {"20:20", null, null, null, null, null, null, null},
                {"21:10", null, null, null, null, null, null, null},
                {"22:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "Horário", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCronograma.setColumnSelectionAllowed(true);
        jTableCronograma.setRowHeight(30);
        jTableCronograma.getTableHeader().setReorderingAllowed(false);
        jScrollPaneCronograma.setViewportView(jTableCronograma);
        jTableCronograma.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableCronograma.getColumnModel().getColumnCount() > 0) {
            jTableCronograma.getColumnModel().getColumn(1).setResizable(false);
            jTableCronograma.getColumnModel().getColumn(2).setResizable(false);
            jTableCronograma.getColumnModel().getColumn(3).setResizable(false);
            jTableCronograma.getColumnModel().getColumn(4).setResizable(false);
            jTableCronograma.getColumnModel().getColumn(5).setResizable(false);
            jTableCronograma.getColumnModel().getColumn(6).setResizable(false);
            jTableCronograma.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabelTituloCronograma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTituloCronograma.setText("Cronograma");

        jLabelTurma.setText("Selecione a turma:");

        jLabelCurso.setText("Selecione o curso:");

        jLabelDisciplina.setText("Selecione a disciplina:");

        jLabelProfessor.setText("Selecione o professor:");

        jSpinnerTurma.setModel(new javax.swing.SpinnerListModel(new String[] {"Selecione", "ENG-MEC-2011", "ENG-MEC-2012", "ENG-MEC-2013", "ENG-MEC-2014"}));

        jSpinnerProfessor.setModel(new javax.swing.SpinnerListModel(new String[] {"Selecione", "André Portugal", "Fábio Elísio", "Gil Jader"}));

        jSpinnerCurso.setModel(new javax.swing.SpinnerListModel(new String[] {"Selecione", "Engenharia Mecanica", "Engenharia da Computação", "Engenharia da Produção"}));

        jSpinnerDisciplina.setModel(new javax.swing.SpinnerListModel(new String[] {"Selecione", "BDII", "Análise de requisitos", "Estrutuda de dados"}));

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloCronograma)
                .addGap(374, 374, 374))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLimpar)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonEnviar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCurso)
                            .addComponent(jSpinnerCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTurma)
                            .addComponent(jSpinnerTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProfessor))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDisciplina)
                            .addComponent(jSpinnerDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneCronograma, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTituloCronograma)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabelCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelDisciplina)
                            .addGap(13, 13, 13)
                            .addComponent(jSpinnerDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelProfessor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinnerProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelTurma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinnerTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPaneCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnviar)
                    .addComponent(jButtonLimpar))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
        String value;

        value = (String) jSpinnerProfessor.getValue();
        value = value+" "+(String) jSpinnerDisciplina.getValue();
        System.out.println(value + "Linha" + jTableCronograma.getSelectedRow() + "Coluna" + jTableCronograma.getSelectedColumn());
        Object o = jTableCronograma.getValueAt(jTableCronograma.getSelectedRow(), jTableCronograma.getSelectedColumn());
        if(o==null){
            jTableCronograma.setValueAt(value, jTableCronograma.getSelectedRow(), jTableCronograma.getSelectedColumn());
            jTableCronograma.setValueAt(value, jTableCronograma.getSelectedRow() + 1, jTableCronograma.getSelectedColumn());
        }

    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:

        String value = "";

        System.out.println(value + "Linha" + jTableCronograma.getSelectedRow() + "Coluna" + jTableCronograma.getSelectedColumn());

        jTableCronograma.setValueAt(value, jTableCronograma.getSelectedRow(), jTableCronograma.getSelectedColumn());
        jTableCronograma.setValueAt(value, jTableCronograma.getSelectedRow() + 1, jTableCronograma.getSelectedColumn());


    }//GEN-LAST:event_jButtonLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelDisciplina;
    private javax.swing.JLabel jLabelProfessor;
    private javax.swing.JLabel jLabelTituloCronograma;
    private javax.swing.JLabel jLabelTurma;
    private javax.swing.JScrollPane jScrollPaneCronograma;
    private javax.swing.JSpinner jSpinnerCurso;
    private javax.swing.JSpinner jSpinnerDisciplina;
    private javax.swing.JSpinner jSpinnerProfessor;
    private javax.swing.JSpinner jSpinnerTurma;
    private javax.swing.JTable jTableCronograma;
    // End of variables declaration//GEN-END:variables
}
